server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dev_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    hikari:
      minimum-idle: 5          # Minimum number of idle connections
      maximum-pool-size: 10    # Maximum number of connections in the pool
      idle-timeout: 30000      # Maximum time (in milliseconds) that a connection can sit idle in the pool
      max-lifetime: 1800000    # Maximum lifetime (in milliseconds) of a connection in the pool
      connection-timeout: 30000 # Maximum time (in milliseconds) to wait for a connection from the pool
      
logging:
  level:
    org.springframework.web: DEBUG
#    org.springframework.security: DEBUG